version: "3"
services:
  api:
    build:
      context: .
    image: api.reidchatham.com-comments:dev
    environment:
      # SLEEP_LENGTH: 5
      # POSTGRES_HOST: db
      # POSTGRES_USER: api_user
      # POSTGRES_PASSWORD: password
      # POSTGRES_DB: api
      DB_USER: api_user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: comments
      # POSTGRES_PORT: 27017
      # EXPOSED_PORT: 443
    # env_file: .env
    ports:
      - 3000:3000
    # volumes:
    #   - ./:/app
    depends_on:
      - "db"
  db:
    image: postgres
    # env_file:
    #   - ./env/postgres.env
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments
    ports:
    - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
